[package]
name = "rust-workflow-2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
derive_more = { version = "2.0.1", features = ["full"] }
drain_filter_polyfill = "0.1.3"
macros = { version = "0.1.0", path = "macros" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
thiserror = "2.0.12"

[workspace]
members = ["macros"]
resolver = "2"
