

[workspace]
members = [
    "macros",
    "aws_adapter",
    "adapter_types",
    "surgeflow_types",
    "examples/hello_world",
    "surgeflow",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
panic = "abort"
