

[workspace]
members = [
    "macros",
    "adapter_types",
    "surgeflow_types",
    "surgeflow",
    "control_server",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
panic = "abort"
