services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # stdin_open: true    # equivalent to -i
    # tty: true           # equivalent to -t
    # restart: "no"